version: 2

sources:
  - name: dev
    database: weather_db
    tables: 
      - name: weather_data
        description: "This table contains weather data for New York City."
        columns:
          - name: id
          - name: city
          - name: temperature
          - name: weather_description
          - name: wind_speed
          - name: time
          - name: inserted_at
          - name: utc_offset
